//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingSociety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_User
    {
        public int REGID { get; set; }
        public string Society_Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
