//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingSociety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society_Add
    {
        public int REGID { get; set; }
        public string POST { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Wing { get; set; }
        public string Flat_No { get; set; }
        public string Time_From { get; set; }
        public string Time_To { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
