//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HousingSociety.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Request
    {
        public int REGID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Wing { get; set; }
        public string Flat_No { get; set; }
        public string Request_Priority { get; set; }
        public string Request_Detail { get; set; }
    }
}
